#!/bin/bash -e
#export CXXFLAGS="-fopenmp"
#export CFLAGS="-fopenmp"
#export CPPFLAGS="-fopenmp"

#export OMP_NUM_THREADS=4
#alias g++='g++ -fopenmp'
#alias gcc='gcc -fopenmp'
cd BUILD
bdir=`pwd`;
echo "$bdir";
IDIR=${bdir//BUILD/INSTALL};
echo "$IDIR";
cmake ../Scribus -DCMAKE_INSTALL_PREFIX:PATH="$IDIR" -DWANT_DEBUG=1 -DWANT_GRAPHICSMAGICK=1 -DWANT_VERSIONING=0 -DWANT_NO_EXAMPLES=1 -DWANT_NO_TEMPLATES=1 -DWANT_NOHEADERINSTALL=1 -DWANT_GUI_LANG=pl_PL
make -j4
make install -j4
