#!/bin/sh -e
#
cd /home/git/scribus.svn/scribus.net/branches/Version14x/

# Get local snapshot copies revision number
OLD=`svn info Scribus | grep -r Wersja | cut -f 2 -d " "`

SVN='svn://scribus.net/branches/Version14x/Scribus/'
# Get current development revision number
NEW=`svn info $SVN | grep -r Wersja | cut -f 2 -d " "`

echo "$OLD"
echo "$NEW"

# Compare for OLD and NEW revision
if [ $NEW -gt $OLD ] ; then
    # update local copies
	svn up
	git add *
	git commit -m "Rev. $NEW update"
fi

exit 0